name: CI

on:
  push:
    branches:
      - main

jobs:
  pull-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull changes on EC2
        run: ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_SSH_PORT }} 'cd /home/ec2-user/DiskoverProject && git pull && python ./EC2Scripts/Utils/switch_env.py'